# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '01-课程分类', 'verbose_name_plural': '01-课程分类'},
        ),
        migrations.AddField(
            model_name='coursesection',
            name='free_trail',
            field=models.BooleanField(default=False, verbose_name='是否可试看'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='section_type',
            field=models.SmallIntegerField(choices=[(0, '文档'), (1, '练习'), (2, '视频')], default=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='课程图片'),
        ),
    ]
