# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181111_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户密码'),
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
